# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pin.xdc

# Block Designs: bd/pwm_design_1/pwm_design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1 || ORIG_REF_NAME==pwm_design_1}]

# IP: bd/pwm_design_1/ip/pwm_design_1_dec_pwm_0_0/pwm_design_1_dec_pwm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1_dec_pwm_0_0 || ORIG_REF_NAME==pwm_design_1_dec_pwm_0_0}]

# IP: bd/pwm_design_1/ip/pwm_design_1_processing_system7_0_0/pwm_design_1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1_processing_system7_0_0 || ORIG_REF_NAME==pwm_design_1_processing_system7_0_0}]

# IP: bd/pwm_design_1/ip/pwm_design_1_processing_system7_0_axi_periph_0/pwm_design_1_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==pwm_design_1_processing_system7_0_axi_periph_0}]

# IP: bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0}]

# IP: bd/pwm_design_1/ip/pwm_design_1_auto_pc_0/pwm_design_1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pwm_design_1_auto_pc_0 || ORIG_REF_NAME==pwm_design_1_auto_pc_0}]

# XDC: bd/pwm_design_1/ip/pwm_design_1_processing_system7_0_0/pwm_design_1_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pwm_design_1_processing_system7_0_0 || ORIG_REF_NAME==pwm_design_1_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==pwm_design_1_rst_processing_system7_0_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/pwm_design_1/ip/pwm_design_1_auto_pc_0/pwm_design_1_auto_pc_0_ooc.xdc

# XDC: bd/pwm_design_1/pwm_design_1_ooc.xdc
