# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Mycode/Verilog/pwm_dec1/pwm_dec1.cache/wt [current_project]
set_property parent.project_path E:/Mycode/Verilog/pwm_dec1/pwm_dec1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths e:/Mycode/Verilog/DecPwmip_repo/dec_pwm_1.0 [current_project]
add_files E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/pwm_design_1.bd
set_property used_in_implementation false [get_files -all e:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/ip/pwm_design_1_processing_system7_0_0/pwm_design_1_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/ip/pwm_design_1_rst_processing_system7_0_100M_0/pwm_design_1_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/ip/pwm_design_1_auto_pc_0/pwm_design_1_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/pwm_design_1_ooc.xdc]
set_property is_locked true [get_files E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/bd/pwm_design_1/pwm_design_1.bd]

read_verilog -library xil_defaultlib E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/sources_1/imports/hdl/pwm_design_1_wrapper.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/constrs_1/new/pin.xdc
set_property used_in_implementation false [get_files E:/Mycode/Verilog/pwm_dec1/pwm_dec1.srcs/constrs_1/new/pin.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top pwm_design_1_wrapper -part xc7z020clg484-1


write_checkpoint -force -noxdef pwm_design_1_wrapper.dcp

catch { report_utilization -file pwm_design_1_wrapper_utilization_synth.rpt -pb pwm_design_1_wrapper_utilization_synth.pb }
